In [1]:
import tensorflow as tf

In [2]:
s1 = tf.constant('hi ')
s2 = tf.constant('people ')
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

b'hi people '


In [3]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

50


In [4]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.multiply(s1,s2)

sess = tf.Session()
print(sess.run(s3))

600


In [5]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.subtract(s1,s2)

sess = tf.Session()
print(sess.run(s3))

-10


In [6]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.divide(s1,s2)

sess = tf.Session()
print(sess.run(s3))

0.6666666666666666


In [7]:
s1 = tf.constant(20)
s2 = tf.constant(3)
s3 = tf.pow(s1,s2)

sess = tf.Session()
print(sess.run(s3))

8000


In [8]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant(30)
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

[35 36 37 38]


In [9]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4])
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

[ 6  8 10 12]


In [10]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4,5,6,7])
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

ValueError: Dimensions must be equal, but are 4 and 7 for 'Add_4' (op: 'Add') with input shapes: [4], [7].

In [12]:
matrix1 = tf.constant([[5., 3.]])
matrix2 = tf.constant([[2.],
                       [2.]])
product = tf.matmul(matrix1, matrix2)


with tf.Session() as sess:
    result = sess.run(product)
    print (result)

[[16.]]


In [13]:
matrix1 = tf.constant([[5,6,9,8],
                      [1,2,8,9],
                      [7,9,5,6],
                      [1,2,3,9]])

In [14]:
matrix2 = tf.matrix_transpose(matrix1)

with tf.Session() as sess:
    result = sess.run(matrix2)
    print (result)

[[5 1 7 1]
 [6 2 9 2]
 [9 8 5 3]
 [8 9 6 9]]
