In [1]:
import tensorflow as tf

In [2]:
a = tf.Variable(3)
b = tf.Variable(3,tf.float32)
c = tf.Variable([2,5,6,9,6])
d = tf.Variable([[2,5,6],[8,5,8], [8,8,1]])
e = tf.Variable('I love TensorFlow')

Instructions for updating:
Colocations handled automatically by placer.


In [3]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))


3
3
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'I love TensorFlow'


In [4]:
price = tf.Variable(20) 
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('original price is : ',sess.run(price))

original price is :  20


In [5]:
price = tf.Variable(30) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(40) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(50) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(60) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

the price is :  30
the price is :  40
the price is :  50
the price is :  60


In [8]:
'''
value = tf.assign(value,newvalue)
'''
price = tf.assign(price,50)
print('new price is : ',sess.run(price))

new price is :  50


In [9]:
for j in range(6) : 
    price = tf.assign(price,price+10)
    print('new price is : ',sess.run(price))

new price is :  60
new price is :  70
new price is :  80
new price is :  90
new price is :  100
new price is :  110
